apiVersion: 1
groups:
    - orgId: 1
      name: System RAM Alert
      folder: Alerts/RAM Alerts/System
      interval: 30s
      rules:
        - uid: feifgdufeeio0e
          title: System RAM Usage
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: fehnonvokrw8wb
              model:
                intervalMs: 1000
                maxDataPoints: 43200
                query: |
                    from(bucket: "monitoring-lpn2")
                      |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                      |> filter(fn: (r) => r["_measurement"] == "mem")
                      |> filter(fn: (r) => r["_field"] == "used_percent")
                      |> filter(fn: (r) => r.host == "lpn2")
                      |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
                      |> yield(name: "last")
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: 7JdIfTn9z
          panelId: 65083
          noDataState: NoData
          execErrState: Error
          annotations:
            __dashboardUid__: 7JdIfTn9z
            __panelId__: "65083"
            description: "El uso de memoria en el host LPN2 ha superado el umbral definido.\n\n\U0001F539 Uso actual: {{ $values.B }}%\n\U0001F539 Umbral: > 80%"
            summary: "\U0001F6A8 Alerta: Uso elevado de RAM en LPN2"
          labels:
            policy: RAM
          isPaused: false
          notification_settings:
            receiver: infra-team-emails
