apiVersion: 1
groups:
    - orgId: 1
      name: System CPU Alert
      folder: Alerts/CPU Alerts/System
      interval: 30s
      rules:
        - uid: eeiffmnc96g3kf
          title: System CPU Usage
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: fehnonvokrw8wb
              model:
                intervalMs: 1000
                maxDataPoints: 43200
                query: "from(bucket: \"monitoring-lpn2\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => \n    r._measurement == \"cpu\" and \n    r.host == \"lpn2\" and \n    r._field == \"usage_idle\" and \n    r.cpu == \"cpu-total\"\n  )\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ _time: r._time, _value: 100.0 - r._value }))\n  |> yield(name: \"cpu_usage\")\n"
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: 7JdIfTn9z
          panelId: 65082
          noDataState: NoData
          execErrState: Error
          annotations:
            __dashboardUid__: 7JdIfTn9z
            __panelId__: "65082"
            description: "El uso total de CPU en el host LPN2 ha superado el umbral crítico.\n\n\U0001F539 Valor actual: {{ $values.B }}%\n\U0001F539 Umbral: > 80%"
            summary: "\U0001F6A8 Alerta: Uso elevado de CPU en LPN2"
          labels:
            policy: CPU
          isPaused: false
          notification_settings:
            receiver: infra-team-emails
