apiVersion: 1
groups:
    - orgId: 1
      name: Write Disk Alert
      folder: Alerts/Disk Alerts
      interval: 1m
      rules:
        - uid: beig2vkk97l6oa
          title: MySQL Write Alert
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: fehnonvokrw8wb
              model:
                intervalMs: 1000
                maxDataPoints: 43200
                query: |
                    from(bucket: "monitoring-lpn2")
                      |> range(start: -10m)
                      |> filter(fn: (r) =>
                        r._measurement == "docker_container_blkio" and
                        r._field == "io_service_bytes_recursive_write" and
                        r.container_name == "mysql"
                      )
                      |> aggregateWindow(every: 1m, fn: mean)
                      |> derivative(unit: 1s, nonNegative: true)
                      |> last()
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 512000
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: YIIzB274z
          panelId: 9
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: YIIzB274z
            __panelId__: "9"
            description: "El contenedor `mysql` está escribiendo más de 500 KiB/s al disco.\nEsto puede deberse a operaciones pesadas, falta de índices o errores.\n\n\U0001F539 Uso actual: {{ $values.B }} bytes/s\n\U0001F539 Container: mysql"
            summary: "\U0001F6A8 Alta escritura en disco por contenedor mysql"
          isPaused: false
          notification_settings:
            receiver: infra-team-emails
        - uid: eeig32dlr4e80a
          title: Telegraf Write Alert
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: fehnonvokrw8wb
              model:
                intervalMs: 1000
                maxDataPoints: 43200
                query: |
                    from(bucket: "monitoring-lpn2")
                      |> range(start: -5m)
                      |> filter(fn: (r) =>
                        r._measurement == "docker_container_blkio" and
                        r._field == "io_service_bytes_recursive_write" and
                        r.container_name == "telegraf"
                      )
                      |> aggregateWindow(every: 1m, fn: mean)
                      |> derivative(unit: 1s, nonNegative: true)
                      |> last()
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 51200
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: YIIzB274z
          panelId: 9
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: YIIzB274z
            __panelId__: "9"
            description: "Se detectó actividad inusual de escritura en disco en `telegraf`.\nEsto podría indicar un error, buffering o problemas con los outputs.\n\n\U0001F539 Uso actual: {{ $values.B }} bytes/s\n\U0001F539 Umbral: > 50 KiB/s"
            summary: ⚠️ Escritura inesperada en contenedor telegraf
          isPaused: false
          notification_settings:
            receiver: infra-team-emails
