version: "3"

services:
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    networks:
      - grafana-network
    depends_on:
      - grafana

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: >
      /bin/sh -c "
        if [ ! -f /etc/letsencrypt/live/lpn3.crabdance.com/fullchain.pem ]; then
          certbot certonly --webroot -w /var/www/certbot --agree-tos --no-eff-email --email gguillaumet011@alumnos.iua.edu.ar -d lpn3.crabdance.com;
        fi;
        trap exit TERM;
        while :; do
          certbot renew --webroot -w /var/www/certbot;
          sleep 30d & wait $${!};
        done;"
    depends_on:
      - nginx
    networks:
      - grafana-network

  #certbot sidecar container
  cert-exporter:
    image: alpine:latest
    container_name: cert-exporter
    depends_on:
      certbot:
        condition: service_healthy
    volumes:
      - certbot-conf:/etc/letsencrypt:ro
      - ./certs:/exported-certs
    entrypoint: >
      /bin/sh -c "
        mkdir -p /exported-certs/lpn3.crabdance.com;

        # Usar symlinks desde /etc/letsencrypt/live (que siempre apuntan al archivo más nuevo)
        cp /etc/letsencrypt/live/lpn3.crabdance.com/fullchain.pem /exported-certs/lpn3.crabdance.com/fullchain.pem;
        cp /etc/letsencrypt/live/lpn3.crabdance.com/privkey.pem /exported-certs/lpn3.crabdance.com/privkey.pem;

        chmod 644 /exported-certs/lpn3.crabdance.com/*.pem;
        chmod 755 /exported-certs /exported-certs/lpn3.crabdance.com;
        chown -R 1000:1000 /exported-certs;

        trap exit TERM;
        while :; do
          echo 'Actualizando certificados exportados...';

          cp /etc/letsencrypt/live/lpn3.crabdance.com/fullchain.pem /exported-certs/lpn3.crabdance.com/fullchain.pem;
          cp /etc/letsencrypt/live/lpn3.crabdance.com/privkey.pem /exported-certs/lpn3.crabdance.com/privkey.pem;

          chmod 644 /exported-certs/lpn3.crabdance.com/*.pem;
          chmod 755 /exported-certs /exported-certs/lpn3.crabdance.com;
          chown -R 1000:1000 /exported-certs;

          sleep 30d & wait $${!};
        done;
      "
    healthcheck:
      test:
        [
          "CMD",
          "test",
          "-f",
          "/exported-certs/lpn3.crabdance.com/fullchain.pem",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - grafana-network
    environment:
      - GF_SERVER_ROOT_URL=https://lpn3.crabdance.com
      - GF_SERVER_SERVE_FROM_SUB_PATH=true

networks:
  grafana-network:
    driver: bridge

volumes:
  certbot-conf:
  certbot-www:
  grafana-storage:
